# Generated by Django 5.2.5 on 2025-08-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionStripe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("strip_pay_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="Id сессии")),
                ("url_link", models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату")),
                (
                    "Payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="users.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "транзакция",
                "verbose_name_plural": "транзакции",
            },
        ),
    ]
