# Generated by Django 5.2.5 on 2025-08-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_transactionstripe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionstripe",
            name="Payment",
        ),
        migrations.AddField(
            model_name="transactionstripe",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="users.payment",
                verbose_name="Платеж",
            ),
        ),
    ]
