# Generated by Django 5.2.5 on 2025-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_pay",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
