# Generated by Django 5.2.4 on 2025-07-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses/previews/", verbose_name="Превью курса"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название урок")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses/previews/", verbose_name="Превью урока"
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
