# Generated by Django 5.2.5 on 2025-08-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Обновление курса"),
        ),
    ]
